### ISSUE TITLE
Automate iOS Notification Extension Service Integration in cordova

### ISSUE THREAD

**Issue by amirhmoradi** [BatchLabs/Batch-Cordova-Plugin#18]
To use latest iOS features, we need to implement a Notification Extension Service by following manual steps in XCODE, as explained in your documentation: https://batch.com/doc/ios/sdk-integration/rich-notifications-setup.html#_integrating-batch-extension-sdk

=> Could you please provide an automated solution to have this added automatically?

Here is some research I've done:
There is a solution to this issue provided here :
https://github.com/infobip/mobile-messaging-cordova-plugin

Which uses the following GEM:
https://github.com/infobip/mobile-messaging-mmine

There is also some work done to use cordova hooks to add the service:
https://github.com/apache/cordova-node-xcode/issues/47#issuecomment-481370180
https://github.com/apache/cordova-ios/issues/582

**Comment by abarisain** [comment]
Thanks for the research.

We opened an internal issue to match this one.

**Comment by abarisain** [comment]
Hello,

Thanks for looking into this.

Due to the complexity of automatically editing Xcode projects, we decided not to pursue this.

My opinion is that this is something that Cordova itself should work on. Ionic Capacitor shows that putting the native projects in the spotlight is the way to go.
