### ISSUE TITLE
error: 'BatchUserBridge.h' file not found with <angled> include; use "quotes" instead

### ISSUE THREAD

**Issue by ossraju** [BatchLabs/Batch-Cordova-Plugin#30]
Pulgin version 5.0.0

when i am building the project through CI,  I have error saying 
`/Plugins/@batch.com/cordova-plugin/BatchUserBridge.m:1:9: error: 'BatchUserBridge.h' file not found with <angled> include; use "quotes" instead
#import <BatchUserBridge.h>
        ^~~~~~~~~~~~~~~~~~~
        "BatchUserBridge.h"
1 error generated.`
is there any work around ?

thanks in advance

**Comment by abarisain** [comment]
Hello,

We do not handle SDK integration tickets here. The next steps are described in our [SDK repository guidelines](https://github.com/BatchLabs/Batch-Android-SDK/blob/master/CONTRIBUTING.md#integration-questions).

You may be asked to provide a minimum reproduction projet and more information about your environment.

Have a nice day,

**Comment by ossraju** [comment]
https://github.com/BatchLabs/Batch-Cordova-Plugin/commit/9eea9f8fc0deb47b385e071843c27758fd42cb0e
issue fixed
